# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"
  - "2.7"

install:
  - pip install -e .
  - pip install pytest pytest-cov codecov

script:
  - pytest --cov wsdiscovery

after_success:
  - codecov
